### ISSUE TITLE
Unable to list horse for sale

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#10]
Customer sent email.  Unable to list their horse for sale. Nothing come up when you click red banner below but this.  Thanks. "No Horses found! Please add your horses.."
![image](https://user-images.githubusercontent.com/31981904/31354895-22ab71b0-ad06-11e7-944d-f90d86558d23.png)

**Comment by itekk** [comment]
1) If no horses added by the member, then the message "No Horses found! Please add your horses.." will show.
2) The icon for adding horse is changed to button. Member can add horses by clicking on "Add Horse" button.

![page](https://user-images.githubusercontent.com/9421142/31396580-60d1b444-ae01-11e7-83f7-b880e7ffc6a4.png)

**Comment by dressagetrainingonline** [comment]
Thank you!
