### ISSUE TITLE
UPDATE footer

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#11]
Hi Mathew. Please add this below our footer.

I've uploaded for easy source code snippet copy and paste here http://www.angelea.com/mathew/footer.html and because GitHub doesn't allow for attachment of html files. :-/

Thanks! -Angelea

**_OR tell me where the footer file is and I'll update it._**

**Comment by itekk** [comment]
Footer content added.

**Comment by dressagetrainingonline** [comment]
Thanks again!
