### ISSUE TITLE
Dressage Score data

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#12]
We have the opportunity to run a test on importing dressage test score data (the directive 0-10 marks and not just the test percentage). The long term goal with this is to be able to offer custom training programs based on what their test scores show they need improvement on and offering them specific videos to check out based on those scores.

What is your desired data format? I am asking to see if we can get 1000 member data cross checked with our active users.

Thanks for letting me know. -Angelea

**Comment by itekk** [comment]
We can use excel file(.xlsx or .xls) for member data.

**Comment by dressagetrainingonline** [comment]
Great. I'll find out what we can get and submit back here.
