### ISSUE TITLE
FYI LimeLight update

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#15]
Just a FYI/heads up... The LimeLight account info was updated just to Cruz Bay Publishing and the email changed to my email address. The log in password remains the same. The email is just now angelea@dressagetrainingonline.com so we'll start getting the invoices directly.

**Comment by jchallberg** [comment]
Are you interested in seeing what our bandwidth and storage usage is? I can get that. Best Regards.
Jo-Ann Challberg
Business Manager
DressageTrainingOnline.com
1 510-499-5565 USA
877-510-1311

**Comment by dressagetrainingonline** [comment]
No. I can get that myself. I was just letting Mathew know as an FYI is all.
