### ISSUE TITLE
Not all emails or Telephone numbers are being stored in BT but they are in admin

### ISSUE THREAD

**Issue by jchallberg** [aimMediaDto/DTO#16]
When I downloaded my decline list I found that not all emails and or Telephone numbers are being stored in BT but they are in admin as it is required to set up a membership.

BT said 
The reason you are not seeing the email or phone number for some of these processor declined transactions is that when the customer was originally stored in your Vault, the email or phone number was not passed via the API. Alternatively, it is possible that this information was removed some time after creating a customer. (no we do not remove information)

If you would like to make sure that your vaulted customers continue to collect phone number and email addresses in Braintree, I recommend having a developer evaluate your server-side API requests. Braintree did not prevent this information from being saved and did not remove this information. There is, or was, likely an issue with the requests sent to Braintree.

**Comment by jchallberg** [comment]
[Failed report issue.xlsx](https://github.com/aimMediaDto/DTO/files/1382923/Failed.report.issue.xlsx)

**Comment by itekk** [comment]
Emails and phone numbers of some old users are missing in BrainTree. It was updated in our database since it is required to set up a membership.

We have to make two updates:
1) We have to update BT with user data from our database via API for all users.
2) We also have to update BT while updating a user in our site (frontend and admin).

This will be 8 hours work. Please confirm to start on this.

**Comment by dressagetrainingonline** [comment]
Mathew - How many hours are we at within the retainer this month already please?

Jo-Ann - Is this something you can move over manually for this and top of next month so we hold on it until top of November please?

**Comment by dressagetrainingonline** [comment]
I understand from Jo-Ann this isn't a super pressing issue for her right now so that manually is ok and we revisit the fix in the coming months. Thanks!
