### ISSUE TITLE
Bogus emails generated from Contact tab beteen 2:48 am to 3:03- many

### ISSUE THREAD

**Issue by jchallberg** [aimMediaDto/DTO#18]
We had a similar issue awhile ago and we added a captcha.  Take a look at the contact from submits form in admin.
![image](https://user-images.githubusercontent.com/1827604/31586990-4b9fa0fa-b18e-11e7-8205-d2610625c694.png)

**Comment by itekk** [comment]
I have updated the captcha and put some extra validation. Let's see if this stops the spam.

**Comment by dressagetrainingonline** [comment]
Thanks much Mathew!!! You're lightning fast with these things and it's greatly appreciated!
