### ISSUE TITLE
Phone field on any sign up page should accept numbers only not alpa characters

### ISSUE THREAD

**Issue by jchallberg** [aimMediaDto/DTO#21]
Chantelle Noble is member
<img width="960" alt="sassy" src="https://user-images.githubusercontent.com/1827604/32065459-b6187244-ba31-11e7-814f-8c4fda9695f3.png">

**Comment by dressagetrainingonline** [comment]
Mathew. Disregard. This is cosmetic and we don't need to do this right now.
