### ISSUE TITLE
Changing campaign focus to 1 one free trial VS 10 day free trial

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#22]
Mathew,

We are shifting focus from the 10 day free trial to offer the month free trial membership with the goal that our Member Concierge combined with more time on the site will make new member stickier than previously achieved. The site has an auto pop up offering the 10 day free trial... is it easy for you to change this out just by receiving a new graphic? I believe Reisa had a campaign setup in IS off this action. Can you confirm this?
![10day-to-30day](https://user-images.githubusercontent.com/31981904/32070893-aea0fa02-ba5b-11e7-808a-774f63db4f8f.jpeg)

**Comment by itekk** [comment]
Yes please send me the new graphic. It's not hard to change it.

**Comment by dressagetrainingonline** [comment]
Here's the revised image for 30 day free. Thanks!
![30-day-free](https://user-images.githubusercontent.com/31981904/33289405-7154a8ce-d38d-11e7-9734-2e60237b9ea0.jpg)

**Comment by itekk** [comment]
1) Do i need to provide the users with one month coupon on second page of email address submission.

OR

2) Just give them the Trial Membership page URL on second page of email address submission.

**Comment by dressagetrainingonline** [comment]
Please direct to the Trial Membership page which we updated to the 30 day details. Thanks! :)

**Comment by itekk** [comment]
Done.

**Comment by dressagetrainingonline** [comment]
Thanks!
