### ISSUE TITLE
10 day free trial off main page does not auto propagate code for sign up

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#23]
This...
![10day-test](https://user-images.githubusercontent.com/31981904/32070985-ed8101f4-ba5b-11e7-9118-acdd9bfcaf74.jpeg)

Does not click through to have the 10 day code applied already nor does the page have a code anywhere on it that one can use to access the 10 day free.
![10day-test2](https://user-images.githubusercontent.com/31981904/32071037-0954b51a-ba5c-11e7-909a-3ec425a2ab41.jpeg)

This should work automatically for future members AND we want to change this from 10 days to one month free ASAP.

Please let me know what you need from me to make this so. Thank you, Angelea

**Comment by itekk** [comment]
This is a 4 Hr work. Can i start on this?

**Comment by dressagetrainingonline** [comment]
Hi Mathew. On these fixes... I'm wondering why these things did not work to begin with when the new site was developed and launch a year ago. Please explain if they were working when you launched this site and if not why and if yes then how they were broken. Thanks!

**Comment by itekk** [comment]
These are the changes we have to do:

1. Add "1 month free trial" verbiage in Trial Registration page
2. Add restriction for not getting double discount with 30 day discount coupon or with other coupons. We were not restricting this with "10 days" option now.
3. We did not put billing start date for "10 days" option, this time since it is 1 month we have to put the billing start date too.

Please confirm to start.

Thanks
Mathew

**Comment by dressagetrainingonline** [comment]
Thanks. I understand on the changes but this does not even work with the 10 day as is... "Does not click through to have the 10 day code applied already nor does the page have a code anywhere on it that one can use to access the 10 day free." When one clicks thru it just takes you to the reg page and (I'm assuming) the discount code for the 10 day free trial should auto propagate in the "Discount Code" text box and there's no language on the from or to page as to what code to manually input. So... it doesn't work as is. Can it, at least, work as is please? Just wondering how we got this far from a launch without detecting this mistake in the system. TIA! :-)

**Comment by itekk** [comment]
1) 10 Days free trial verbiage added.
2) Payment start date added.
3) This is trial membership page. No need to populate 10 days code in coupon field.

Take a look.

![trial](https://user-images.githubusercontent.com/9421142/32378971-35679ba0-c0d2-11e7-87ca-c4c98c73f066.png)

Please tell if you need any change other than this.

**Comment by dressagetrainingonline** [comment]
Thanks Mathew. Now on to converting this 10 day free to 30 day free instead... From how I've managed backends before something like this is quite simple, just changing a few lines of code here and there. Is this something you would do and if so how long would it take you please? Thank you again! :) -Angelea

**Comment by itekk** [comment]
1) 10 day free trial changed to 30 day free trial.
2) In trial registration page, member gets 30 days free trial. But he will not get extra 30 days using coupon code.

Is this okay for you?

**Comment by dressagetrainingonline** [comment]
This is TERRIFIC Mathew! Thanks. The top "10 day" needs to be updated to "30 days" (screen cap attached) and the bottom copy needs to reflect the change from 10-30 days so...

![trydtofreefor10days](https://user-images.githubusercontent.com/31981904/32575313-a0d8b464-c4a1-11e7-8fcb-39c5f2eb3e8c.jpeg)

...remembered that GitHub doesn't accept HTML & to save you a few sec I just put the new copy up at http://www.angelea.com/itekk/ that goes below the yellow "Complete Registration" button.

Again thanks much! This will be just perfect! Once this is completely dialed in, we will update all the ads to point here instead. :)

**Comment by itekk** [comment]
Text changed.

**Comment by dressagetrainingonline** [comment]
It's just perfect Mathew! Thank you so much! :)
