### ISSUE TITLE
Broken content links on site

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#24]
There's quite a few broken links on the site. I want to fix them.

Please let me know where I go to remove links from this page https://dressagetrainingonline.com/frontend/web/site/specialityvideos as the "Young Rider Clinic, Demonstration and Discussion with Volker.." and "Creating the Freestyle by Teri Gallo" among others go to broken pages https://dressagetrainingonline.com/frontend/web/site/video?trainer_id=47

Thanks! -Angelea

**Comment by itekk** [comment]
I have removed the authors having no videos from page using code. Is that okay for you?

**Comment by dressagetrainingonline** [comment]
Ok. Thanks.

FYI, I can do little things like that if you just tell me where they are in structure. I've been developing sites since 1996 so definitely know my way around minor edits and that can save you time to focus on more important projects.
