### ISSUE TITLE
ClickFunnel link used anywhere

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#25]
Hi. Do you know if this link https://dressagetrainingonline.clickfunnels.com/order-formgj5ldjg6 from the ClickFunnel account is active anywhere on the website? It seems like it was setup but never used and we're paying a monthly fee for it so if we're not using it, I'd like to cancel the service.

TIA!

**Comment by dressagetrainingonline** [comment]
OR really anything with ClickFunnel. Thanks!

**Comment by jchallberg** [comment]
Sorry. I know nothing about clipck funnel. That was something Reisa did.

Jo-Ann Challberg
Business Manager
510-470 9732
