### ISSUE TITLE
Pls change Admin Panel for Michelle benz   whitebridgestables@outlook.com	

### ISSUE THREAD

**Issue by jchallberg** [aimMediaDto/DTO#26]
Customer wanted 12 mos and signed up for 1 month- should show 12 month term expires 11-8-18.  Subscription ID has been updated.

**Comment by dressagetrainingonline** [comment]
Jo-Ann did you mean to assign this to Mathew? There's no assignees.

**Comment by jchallberg** [comment]
I do not believe I am permissioned to assign- the admin is or at least that
has how it worked in the past.  He got them before but I am not sure of
your set up.

--
Thank you very much for choosing DTO! Cheers!

*The Happy DTO Member Support Team *| DressageTrainingOnline.com | 877 510
1311

**Comment by itekk** [comment]
Updated.

**Comment by dressagetrainingonline** [comment]
Thanks Mathew!
