### ISSUE TITLE
Update 10 to 30 on the video pops

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#27]
Hi Mathew. Please update the pops ups on the video pages to read 30 days instead of the 10 days. Thanks!
![10-30-day-pops](https://user-images.githubusercontent.com/31981904/32664769-3fb37c90-c600-11e7-8f1e-faf8172e629f.jpeg)

**Comment by dressagetrainingonline** [comment]
AND where could I go to update the copy at the top of these pages please. For example this particular one says "11/2009 Jean Bemelman coaching professional trainer Carl Hester, Level: I1/S/Advanced, Collection. Day 2, KBIS Convention
Featuring: Jean Bemelmans Rider: Carl Hester Horse: Uthopia, 8 yr. old, DWB x Metall, Level: I1/S/Advanced Owner: Sasha Stewart. Intermediare level, focus on collection. " but I'd like to massage the copy on it and other pages and CMS editing capabilities seem limited. Thanks! -Angelea

**Comment by itekk** [comment]
1) "10 Day trial" text replaced with "30 Day trial".
2) To change video details follow the steps below.
Login to admin side.
Click on "Manage Video" section under "OBJECT / VIDEO MANAGEMENT" tab. This will list all videos.
Click on "Edit" button of particular video.
"Video Name" and "Description" in this page is the top content of video page. You can change it from here.

**Comment by dressagetrainingonline** [comment]
Thanks so much on the CMS location for video copy editing! :)
