### ISSUE TITLE
Update trialmembership page auto play video

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#28]
Hi Mathew. Please update the auto play video at https://dressagetrainingonline.com/frontend/web/site/trialmembership with this testimonial video at http://www.angelea.com/itekk/testimonial.MP4

Many thanks in advance! This new 30 day free push is coming into place! :)

**Comment by dressagetrainingonline** [comment]
I'll also get some revised copy for this left half page to you shortly.

If you could tell me where this is in the structure, I can do the copy edits myself and save your time for more important programming items. :) TIA!

**Comment by itekk** [comment]
Video changed in Trial Membership page.

**Comment by dressagetrainingonline** [comment]
Thanks! I'll also have some revised copy for this left half page to you shortly.

Please tell me where this is so I can do the copy edits myself and save your time for more important programming items. :) TIA!

**Comment by itekk** [comment]
You need to update this file /var/www/html/dressagetrainingonline.com/public/frontend/views/site/trialmembership.php

You need to use SVN for this. Please give me the email to send you the access to SVN

**Comment by dressagetrainingonline** [comment]
angelea@angelea.com and could I just FTP or sFTP and to pull/push that file in the directory no?

For improved mobile viewing, we actually need to swap all the content in the left table to the right and vice versa so the sign up info will appear first in mobile. Make sense? I'll attach a screen cap showing a rough mock of the content swapping. If you have them in tables this is just a few seconds to change so I hope that might be your framework on this page. Leading with the video on desktop makes logical English reading sense but how it responses to mobile gives way too much to scroll before they get to the actual sign up part. TIA for letting me know on this!

![swapped](https://user-images.githubusercontent.com/31981904/32905558-441bf20e-cac8-11e7-86ee-ff048038d129.jpg)

**Comment by dressagetrainingonline** [comment]
We actually need to do the same on swapping the videos on this page AND swapping the left and right columns so mobile users don't have to scroll so far to point of purchase. https://dressagetrainingonline.com/frontend/web/site/gift

**Comment by itekk** [comment]
Left and right content swapped in below pages.
1) https://dressagetrainingonline.com/frontend/web/site/registration
2) https://dressagetrainingonline.com/frontend/web/site/trialmembership
3) https://dressagetrainingonline.com/frontend/web/site/gift
4) https://dressagetrainingonline.com/frontend/web/site/register_giftcard
5) https://dressagetrainingonline.com/frontend/web/site/horsemembership
6) https://dressagetrainingonline.com/frontend/web/site/advertisers

**Comment by itekk** [comment]
Do not FTP the file to the directory. File must upload to directory through SVN.

**Comment by dressagetrainingonline** [comment]
Why SVN. That's such a pain when FTP is sooooo easy and fast.

**Comment by dressagetrainingonline** [comment]
Mathew please I just want some flexibility to make copy changes so I don't have to bother you for every single little word change here and there and reserver your time for actual coding stuff. SpringLoops is just so many extra steps over grabbing a file down off FTP, making a change, and uploading (and I'll keep an original like I have since 1995 in case I break something).

**Comment by dressagetrainingonline** [comment]
Stuff like this... on this page https://dressagetrainingonline.com/frontend/web/site/registration the copy top left above the initial textbox reads "Member Sign Up & Pricing. Sign up now to take your riding to the next level for only $28.80 per month. Satisfaction is guaranteed!" YET the actual price they are signing up for is $36. If I could FTP, I could go in right now, pull that file, fix that copy, push it back and voila. Done!

We're trying to run a Facebook ad and launch it right now and my hands are tied because I can't make simple changes like that to make the landing page correct.

I need to make this change and a little other copy changes at the top of this page.

**Comment by dressagetrainingonline** [comment]
AND I want to create custom landing pages for the holiday promotions we're wanting to do. I completely understand this Github process of work flow for major site changes but for simple copy updates this process just takes way too long. That said, I know you're lightning fast with changes BUT I need this copy changed right now and I can't do it and because of our extensive time difference if I needed something late in my afternoon it wouldn't happen. Please help me and allow for FTP which is my preferred method of file transfer since the mid 90s.

**Comment by dressagetrainingonline** [comment]
I do (very much) appreciate how fast you are but I've never worked in this way before and lack of being able to make tiny tweaks on my own is a huge challenge.

**Comment by itekk** [comment]
Here is the ftp details:
**SFTP port:22**
104.130.29.96
User: dtolive
Pass: dt0liV31

You can ftp the changes directly, once you make the change, just let me know the file name and i can put it into SVN too. 

We need to do this so in case if have any server disaster, we can bring back our server easily.

**Comment by dressagetrainingonline** [comment]
Ok. Thank you! I have to do other projects today so can you please fix this? Not sure how it's gone on since the new site launch last year and been wrong without anyone catching it. :-/

on this page https://dressagetrainingonline.com/frontend/web/site/registration the copy top left above the initial textbox reads "Member Sign Up & Pricing. Sign up now to take your riding to the next level for only $28.80 per month. Satisfaction is guaranteed!" YET the actual price they are signing up for is $36.

**Comment by itekk** [comment]
$28.80 per month if 12 month plan is selected.

See below screenshot
![registration](https://user-images.githubusercontent.com/9421142/33058235-a6981c6a-ceb4-11e7-936c-1c1894715043.png)

**Comment by dressagetrainingonline** [comment]
Thanks Mathew. Still... that copy is deceiving so please update this...
Member Sign Up & Pricing
Sign up now to take your riding to the next level for only $28.80 per month. Satisfaction is guaranteed!

to read...
DTO Membership
Sign up now to take your riding to the next level!

Less is more. :)

**Comment by itekk** [comment]
Text changed in registration page.

**Comment by dressagetrainingonline** [comment]
Thanks!
