### ISSUE TITLE
More - swap Reisa video with Karen Abeyta vid

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#29]
As with the registration page for trial membership 30 day please remove the Reisa video and replace it with the Karen Abeyta video on these pages (or really any pages that has the Reisa video) please.

https://dressagetrainingonline.com/frontend/web/site/gift
https://dressagetrainingonline.com/frontend/web/site/registration

**Comment by itekk** [comment]
Done in below pages.
1) https://dressagetrainingonline.com/frontend/web/site/registration
2) https://dressagetrainingonline.com/frontend/web/site/trialmembership
3) https://dressagetrainingonline.com/frontend/web/site/gift
4) https://dressagetrainingonline.com/frontend/web/site/register_giftcard
5) https://dressagetrainingonline.com/frontend/web/site/horsemembership

**Comment by dressagetrainingonline** [comment]
Thank you Mathew!!!
