### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#3]
When someone does a search on google or yahoo for "counter bend" or "use of counterbend", the attached video should come up because it's titled "used of counter bend". However, it does come up at all. How can this be remedied?
<img width="1440" alt="27399764-b4e226cc-5672-11e7-84cc-5810f5f19be1" src="https://user-images.githubusercontent.com/31981904/30472453-11f53a8a-9a1a-11e7-8b03-9e974549be17.png">

**Comment by itekk** [comment]
1. Need to set page title as video name.
2. Need to setup search engine friendly URLs for all existing videos (1000 + videos) and for new videos.

It will take 6 to 8 hrs. Can i start work on this?

**Comment by dressagetrainingonline** [comment]
To do what you suggest, how does this affect my SEO and affect existing links that are out there in the world through newsletters and imbedded web banners, landing pages, etc., etc.,  Reisa Bonetti-Sullivan
reisa@sbcglobal.net925.324.5444




    On Friday, June 30, 2017 12:44 AM, itekk <notifications@github.com> wrote:_



   - Need to set page title as video name.
   - Need to setup search engine friendly URLs for all existing videos (1000 + videos) and for new videos.
It will take 6 to 8 hrs. Can i start work on this?—

**Comment by itekk** [comment]
After seo url implementation, the video will work on both seo url and old url.

**Comment by dressagetrainingonline** [comment]
We can start on this, but it is of utmost importance that all of my old url's will redirect. I have many url's embedded in newsletters, social media, landing pages, google ads, bing ads, fb ads, web banners and the list goes on. 
Also, will this affect my SEO ratings negatively in any way, even temporarily? Reisa Bonetti-Sullivan
reisa@sbcglobal.net925.324.5444




    On Monday, July 3, 2017 11:03 PM, itekk <notifications@github.com> wrote:


 After seo url implementation, the video will work on both seo url and old url.—

**Comment by dressagetrainingonline** [comment]
Is this already implemented from last month? **If not, we can wait on it** and if so just let me know. Either way I'll close this after you reply Mathew. Thanks! -Angelea

**Comment by itekk** [comment]
I am working on it and will complete it by mid of next week.

**Comment by dressagetrainingonline** [comment]
Thanks. Just comment here when complete please and I'll close this issue / upgrade. Thanks again! -Angelea

**Comment by dressagetrainingonline** [comment]
Hi again! Please let me know when this is complete. Thanks! -Angelea

**Comment by itekk** [comment]
Yes please close this.
