### ISSUE TITLE
Doing away with $5 USDF charge

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#30]
USDF wants to do away with the $5 DTO charge which is actually less end of quarter admin on the DTO side. We still want the member credits for eLearning with USDF University just don't want them to be prompted to pay.

Can you turn off the pay component please?

**Comment by itekk** [comment]
Payment skipped.

**Comment by dressagetrainingonline** [comment]
Awesome! Thanks!
