### ISSUE TITLE
Videos pop ups 10 to 30 days

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#31]
All the videos have a timed pop for click through to registration that say 10 days. Please update them to our 30 day instead now. Thanks!

**Comment by itekk** [comment]
I changed 10 days to 30 days in whole site. Can you please clear the browser cache and try.

**Comment by dressagetrainingonline** [comment]
I don't know all the places it is listed but the ones I checked look great. Thanks very much!
