### ISSUE TITLE
Customize Member Data

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#33]
Mathew. We have some custom data for members. I will include a single sample. I'm interested in overlaying this data on our matching members to create custom content experiences for members such as recommending videos based on their dressage test scores. Please take a look and let me know how much time this would take to write a script that works with the site db and how long it would take to run a test on approximately 400 matches.
[sample.xlsx](https://github.com/aimMediaDto/DTO/files/1511486/sample.xlsx)

Entry ID | Horse | First Name | Last Name | Citizenship | Status | Term Reason | Ride Time | Class Text | Class Name | Class Time | Class Date | Ring | Test Name | Judge Name E | Country E | Total Score E | Total Percent E | Rank E | Judge Name H | Country H | Total Score H | Total Percent H | Rank H | Judge Name C | Country C | Total Score C | Total Percent C | Rank C | Judge Name M | Country M | Total Score M | Total Percent M | Rank M | Judge Name B | Country B | Total Score B | Total Percent B | Rank B | Total Score | Total Percent | Place | Breed | Height | Color | Sex | Sire | Dam | Dam's Sire | Birth Country | Birth Year | Breeder | Owner First Name | Owner Last Name | Horse USEF | Rider USEF
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
313 | Prom Date | Heather | Oleson | US | Open | No | 11:48:00 AM | 130A | First Level Test 2 OPEN CHAMPIONSHIP | 11:18:00 AM | 9/9/17 | Indigo Rescue | First Level, Test 2 2015 |   |   | 0 | 0 | 0 |   |   | 0 | 0 | 0 | Steiner |   | 237 | 0.740625 | 0 |   |   | 0 | 0 | 0 |   |   | 0 | 0 | 0 | 237 | 0.740625 | 3 | HANN | 16.2 | Black bay | Gelding | Pablo | Her Highness O | Hohenstein | US | 2008 | Jennifer Lind | Zoeanne | Arrington | 5273825 | 229056

**Comment by itekk** [comment]
Can you please explain little more.

**Comment by dressagetrainingonline** [comment]
Sure! :) It's interesting to take competition results from member dressage tests to see what movements they might need help/training in then that information could be used to recommend specific videos to members. We could customize their experiences based on what they need help with and become a true virtual online trainer.

**Comment by itekk** [comment]
Can we setup a time to talk on the phone this morning?

**Comment by dressagetrainingonline** [comment]
I'm flexible today. Now is good or in an hour?

**Comment by dressagetrainingonline** [comment]
Hi Mathew. I got this approved for the manual test. I'm attaching the spreadsheet to match rider name, test, class, judge, percentage with our members so we can match this data to send them custom emails of videos that might be helpful considering what level they are competing and how their scores rank. Thanks for your time on the phone today! :)
[Show Results - Matching (400).xlsx](https://github.com/aimMediaDto/DTO/files/1519268/Show.Results.-.Matching.400.xlsx)

**Comment by dressagetrainingonline** [comment]
Thanks for the email confirmation this will be complete by the 12th! Looking forward to testing this possible regular site enhancement. :)

**Comment by dressagetrainingonline** [comment]
Looking forward to receiving this tomorrow! Yeah! :)

**Comment by itekk** [comment]
1) The spreadsheet containing the custom data for members is imported to the site using their name provided.

2) To view the custom data follow the below steps.
    Login to Admin side.
    Go to "Member Scores" section under "Admin" tab in left nav (https://dressagetrainingonline.com/admin/site/memberscores).

3) Full details of a member can be viewed by clicking the name of the member.

4) Filter Criteria :
Filtering is according to "Total Percentage".

    If we provide a search value in first search box, all the members with total percentage greater than or equal to that value will be listed.
    If we provide a search value in second search box, all the members with total percentage lesser than or equal to that value will be listed.
    If we provide a search values in both search boxes, all the members with total percentage between these values will be listed.

5) The following users occurs more than once in the user table. Can you please specify to which user you want to associate the member data.
            1. Linda Thee
            2. Dorie Forte
            3. Bridget Rogers
            4. Barbara Progess
            5. Michelle Benz
            6. Emily Emond
            7. Cara Barker Yellott
            8. Nancy Davis
            9. Patricia Ruppert
            10. Jeanine Holtsberg
            11. Kelly Walker
            12. Erika Murphy
            13. Robin Smith
            14. Lourdes Ariza
            15. Stacy Boles
            16. Lisa Lewis
            17. Paige Huff
            18. Robin Hessel
            19. Lani Wicks Reilly
            20. Julia Eiden
            21. Barbara Bytwerk
            22. Kim Ferrari
            23. Christi Pope
            24. Rachel DeMarcus
            25. Kimberly Taylor
            26. Debra Landreville
            27. Barbara Sith
            28. Robin Wellington
            29. Loren Legg
            30. Sophie Bayer
            31. Jennifer Williams
            32. Sue Rudmann
            33. Elaine Hayes
            34. Gail Abele
            35. Sandra Cain
            36. Sarah Chau
            37. Elizabeth Hotchkiss
            38. Jodi Reynolds
            39. Lisa Freund
            40. Rebecca Sullivan
            41. Anna Jaffe
            42. Jenna Johns
            43. Rebekah Wesatzke
            44. Sara Eberly
            45. Sharmane Fontenot
            46. Sylvia Schafer

**Comment by dressagetrainingonline** [comment]
Mathew. I'll drive more into this this afternoon as I have to put out PayPal transition fires today. :( this is going to be great in the long but we need to be able to sort by the class level like "Third Level" or "First Level" or "Grand Prix" because I'll ultimately need to tag members (or future members) by their level in Infusionsoft (of Salesforce if we switch) because we'll send out custom emails based on 1. Level and 2. Percentage score. I apologize if I wasn't 100% clear but I thought you understood the matching needed. TIA for letting me know and great work so far! :)

**Comment by dressagetrainingonline** [comment]
Put Limelight pull down to S3 as priority this week. I'm working on the non matching member emails right now so if there's more programming that needs to be done on this it can start after we have a backup of Limelight. Thanks! :)
