### ISSUE TITLE
Housekeeping database

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#35]
Hi Mathew. There's lots of matvar test users in the DB on Admin. Could you "clean up" these and remove all matvar and other testing users that have been created so I can more easily pull down states from coupon management please?

**Comment by dressagetrainingonline** [comment]
I was checking Admin today doing customer service and looked at coupons. It appears this is complete. Is that correct?

**Comment by itekk** [comment]
Could not find any "Complete" status in admin side coupon section. Can you please share a screenshot?

**Comment by itekk** [comment]
Test accounts deleted.

**Comment by dressagetrainingonline** [comment]
Much appreciated!
