### ISSUE TITLE
Still showing up Reisa vid

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#36]
Hi there. This one is still showing up thumbnail of Reisa instead of the testimonial https://dressagetrainingonline.com/frontend/web/site/registration and I cleared history and cache. It plays the testimonial vid which is correct but we need to pull Reisa's thumbnail off. TIA!

**Comment by itekk** [comment]
New poster image is setup. Please clear cache and check it.

**Comment by dressagetrainingonline** [comment]
Pops up Karen thumbnail then reverts to Reisa. Cleared cache/history & restarted twice. Please fix. Thanks! I'll email you the screen video.

**Comment by itekk** [comment]
It was an issue only in Safari browser. Now fixed.

**Comment by dressagetrainingonline** [comment]
You're wonderful. Thank you!
