### ISSUE TITLE
Clean up header nav

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#37]
Hi Mathew. Let's clean up the navigation in the header! :) From left to right.

- Add "Get Started" far left linking to https://dressagetrainingonline.com/frontend/web/site/registration
- Change "Training Videos" to "Videos" and drop downs stay the same
- Change "Articles and Exercises" to "Diagrams"
- Remove "Shop Horses & Goods"
- "Evaluate Your Ride" same copy and link
- Remove "Resources/Products"
- Remove "Global Events/Listings"
- Remove "Blog"
- Add "Gift A Membership" and goes to https://dressagetrainingonline.com/frontend/web/site/gift
- Add "Login" and goes to https://dressagetrainingonline.com/frontend/web/site/login
- Add "Join" and goes to https://dressagetrainingonline.com/frontend/web/site/registration

So... the new resulting header nav will be from left to right
Get Started
Videos
Diagrams
Evaluate Your Ride
Gift A Membership
Login
Join

**AND** please change out the top left header logo so it doesn't have the DressageTrainingOnline.com + tag line portion. Attached and same size as I just deleted the extra copy.
![dressagetrainingonline_logo-new](https://user-images.githubusercontent.com/31981904/33502161-04bfa100-d6ad-11e7-8401-41e193683ee7.png)

**Comment by dressagetrainingonline** [comment]
Hi Mathew. I thought you were putting this live 2 days ago and then again yesterday. Please let me know when this will be process. Thanks so much! :)

**Comment by itekk** [comment]
Almost completed. I can make it live in maximum of 1-2 hours.

**Comment by itekk** [comment]
Done.

**Comment by dressagetrainingonline** [comment]
This is lovely and much appreciated Mathew. Thank you!
