### ISSUE TITLE
Going away from Limelight

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#38]
It's all in the research stage so I'm not sure where or when we'll move the media but I do know we'd like to move away from Limelight eventually.

You can write (The ETO folks mention you did one to pull off their data I believe) an API that would pull off our media from Limelight (matching Limelight IDs with our site db for titles/descriptions) and then migrate it to another platform like say... Brightcove correct?

All the video embeds/links on the website would need to be updated after the migration is tested of course but that's also scriptable?

Again, I'm in the research phase on this but answers to the questions will definitely drive the direction we go for video hosting. Thanks!

**Comment by dressagetrainingonline** [comment]
Mathew we spoke on the phone about this one and you had said you wrote and API to pull off Reisa's content from Limelight so I'm assuming you could use the same exact API for DTO if we want to pull down data and migrate to another platform like Brightcove. I assume being a hosting company, Limelight has redundant data but regardless if we move platforms or not, it would still be nice to have backups of this data on HD or just sitting on AWS as storage in the event Limelight has a catastrophic system failure.

Let me know when this could start and how many hours it would take you please and thank you. :-D

**Comment by dressagetrainingonline** [comment]
I received approval that we could move media away from Limelight and on to a better platform like Brightcove. Please reply by late morning eastern time tomorrow as I have to provide these answers or at least a draft by midday:

1. What date can run the API for DTO to pull down all the media from Limelight
2. After the pull down what sort of data would we have and how could I sift through it to enhance the tags/categories on videos to improve indexing
3. If you just need S3 access to push it to the new platform
4. Approximately how many hours this will take & estimate completion date

**Comment by itekk** [comment]
1) What date can run the API for DTO to pull down all the media from Limelight
I can start work on 13th Wednesday.

2) After the pull down what sort of data would we have and how could I sift through it to enhance the tags/categories on videos to improve indexing
For each video in limelight, we get category, tags, title and description. I can give you this data in an excel for you add/update it,

3) If you just need S3 access to push it to the new platform
Yes, please setup an S3 account and give me details.

4) Approximately how many hours this will take & estimate completion date
    We need to process around 4000 videos.
    First step is to pull down all videos used in site from limelight to amazon S3 (Using API).
    Then push these videos and related data from amazon S3 to Brightcove platform (Using API).
    Next step is to change the limelight code to brightcove code in whole site.
    This is a big move. So thorough testing is needed.
    One week time to do the APIs and other code changes.
    This is a  24-40 Hrs work.

Please approve to continue.

**Comment by dressagetrainingonline** [comment]
Thanks Mathew! Now that I have this, I can run it by higher and find out if we can get approval but I need refined info to go to them today. So, to start, how many hours/time would that be and could you possibly give a more refined window than 24-40 hours please?

1. Pull down all videos used in site from Limelight to amazon S3 (Using API).
2. Push these videos and related data from amazon S3 to new media platform (Using API).

Thanks again!

**Comment by itekk** [comment]
No i won't be able to give you a more refined window than 24-40 hrs, because we have close to 4000 videos, we can never know what type of issue we may phase while doing the move.
Also, we can never know how the new system will work with the players we have in DTO.

**Comment by dressagetrainingonline** [comment]
Ok. Thanks. Please how much time if we only do...

1. Pull down all videos used in site from Limelight to amazon S3 (Using API).
2. Push these videos and related data from amazon S3 to new media platform (Using API).

just to start and we don't change the site?

**Comment by itekk** [comment]
16-24 hrs to do the steps 1 & 2 only.

**Comment by dressagetrainingonline** [comment]
Thanks! This way I can break it down for them! Much appreciated!

And can that be started on 13th and completed in one week?

**Comment by itekk** [comment]
yes

**Comment by dressagetrainingonline** [comment]
Thanks again. Very helpful! Following up after meeting. If we just want to do #1 - Pull down all videos used in site from Limelight to amazon S3 (Using API) - then that would take how long starting on the 13th? Completed in by EOD Friday the 15th?

**Comment by itekk** [comment]
This will be 8-10 hrs work. Yes i can complete it by 15th.

**Comment by dressagetrainingonline** [comment]
Wonderful! Please go ahead with this. **Do you need any Amazon (or any other) information from me to start/finish?** I know AIM uses AWS but haven't worked with it yet personally. This will include the spreadsheet we can work on improving the titles in as well correct? I really want to enhance the titles and descriptions on our media so we can improve the search results. THANKS!

**Comment by itekk** [comment]
Please create an account in AWS and give me credentials.

**Comment by dressagetrainingonline** [comment]
fXjL96Ief8BAIlziN14llKpSIhbIVW3/47B32beY

**Comment by dressagetrainingonline** [comment]
You on this????

**Comment by itekk** [comment]
Yes started on this, so far going fine to meet our Friday deadline. I can know for sure by tomorrow.

**Comment by dressagetrainingonline** [comment]
Excellent. Let me know in the morning please. Email is easier so I don't have to come here. Thanks!

**Comment by itekk** [comment]
We have pull down all videos used in site from Limelight to amazon S3 using API.

**DTO AWS**:
    Sign-in URL: https://771489328014.signin.aws.amazon.com/console
    User name: dto-iam
    Password: agddsIlFP85I
 
    You can view the videos here:
    https://s3.console.aws.amazon.com/s3/buckets/dressagetodayonline/?region=us-east-2&tab=overview

**Limelight**:
    http://assets.delvenetworks.com/
    User name: angelea@dressagetrainingonline.com
    Password:   IAgDzZ/1iR7aTF

**Comment by dressagetrainingonline** [comment]
Make this GitHub private so this information isn't available to just anyone who happens upon this URL and please remove Jo-Ann's account from it as well. Thank you.
