### ISSUE TITLE
Unable to Renew Existing Member 3 month Gold Membership Anne Svensson

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#4]
This customer tried to update to Gold for 3 months twice. I just tried to do it and it said the subscription was renewed but it is not. Did not get updated in BT or admin. I can not find any duplicate account or payment.

You have been renewed subscription successfully

Subscription Term : 3 Month
Package : Gold
Thank you !

1. cancelled exiting subscription and creating new subscription in BT
2. Customer will bill tmo when old membership ends
3. Updated subscription ID in admin

Needed follow up

1. Identify problem and fix issue
2. Update admin panel with new Term expire date

**Comment by itekk** [comment]
1. Updated admin panel with new Term expire date.
2. No issue find with subscription renewal.
This customer tried to update to Gold for 3 months twice.
So her Number of billing Cycles of subscription (hyrj3g) increased to 3 and expiry date in Braintree set to 03/02/2018.

But you cancelled that subscription and created a new one.

**Comment by dressagetrainingonline** [comment]
There was an issue.  The customer tried and I tried and it said successful.  She thought she extended so it is an issue as it would have turned off and we did not collect money. Please research further.  Best Regards.
Jo-Ann Challberg
Business Director
DressageTrainingOnline.com
EnthusiastTrainingOnline.comMyDressageStats.com
1 510-499-5565 USA
877-510-1311

**Comment by dressagetrainingonline** [comment]
Howdy Mathew. I'd like to close this issue if it is resolved. Please comment and let me know. Thanks. -Angelea :)

**Comment by itekk** [comment]
Completed.

After the plan renewal in "Update Subscription" page, the new expiry date will show on "Thanks" Page and "Update Subscription" Page.

**Comment by dressagetrainingonline** [comment]
Thank you Mathew!
