### ISSUE TITLE
30 day free membership only giving members 10 day free

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#40]
Mathew... Several new members have complained they submitted a registration for a 30 day free membership but only have received a 10 day free. One is polly schmidt. Please fix this. Thanks!

**Comment by itekk** [comment]
Member polly schmidt registered on Oct 28th. We implemented 30 days free trial on November.

**Comment by dressagetrainingonline** [comment]
Thanks! She evidently saw the 30 day free after she signed up then. Is it a matter of me just updating her coupon a 30 day free one and that will give her the 30 days?

**Comment by dressagetrainingonline** [comment]
Nevermind. I sorted it another way. :)
