### ISSUE TITLE
Remove Jo-Ann's # & address please

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#41]
Just saw this at https://dressagetrainingonline.com/frontend/web/site/terms and her personal number/addy needs to be removed from the site please (or 510.499.5565) and (You may also send correspondance to 3130 Balfour Rd., ste. D, Brentwood, CA, 94513.).

Thanks! :)

**Comment by itekk** [comment]
Done.

**Comment by dressagetrainingonline** [comment]
Perfect! Much appreciated!
