### ISSUE TITLE
10 day free still popping up in spots

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#43]
Please update to http://dressagetrainingonline.com/axel-steiner-11-30-17-third-level-basics-v3.html?inf_contact_key=572d832c75e07338f4687e91537a8945 30 days free. Thanks!

**Comment by itekk** [comment]
Done.
Please clear cache before checking.

**Comment by dressagetrainingonline** [comment]
Super duper! Thank you! :)
