### ISSUE TITLE
Registration follow up page direct to Member's Profile Page

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#46]
After successful member registration please take them directly to their Member Profile Page instead of this up-selling books page at https://dressagetrainingonline.com/frontend/web/site/optionalpurchases

Thanks!

**Comment by itekk** [comment]
Done.
Clicking on "Continue" button will navigate to Member profile page.

**Comment by dressagetrainingonline** [comment]
THANK YOU!
