### ISSUE TITLE
User amiefulks prematurely charged on a 10-day free trial from our Facebook

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#5]
Mathew,
Member details below. She started the 10-day free trial from our Facebook and said she was already charged. Please take a look at this path in the system. I updated her account to the house 30 day free trial to retain her as a member this morning thus it’s no longer the FB code in details below.

Amie Fulks
amiefulks
amiefulks@yahoo.com
Facebook
House2015
Sep 24, 2017
Gold
3 - Months Plan
Dec 23, 2017

**Comment by dressagetrainingonline** [comment]
Expiry date changed to Jan 24, 2018 in database.

**Comment by itekk** [comment]
Expiry date changed to Jan 24, 2018 in database.

**Comment by itekk** [comment]
Can i close this issue?
