### ISSUE TITLE
AIM corp footer addition

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#6]
Hi Mathew. Please add this below our footer.

   <center>
    <div class="col-sm-12 copyright" style="padding-bottom: 0px;">
      <p><span id="dnn_dnnCopyright_lblCopyright" class="copyrightText">Copyright 2017 by Cruz Bay Publishing, Inc. an Active Interest Media company</span>
    </div>
	<div class="col-md-12 col-xs-12 copyright" style="padding: 0px;">
      <p><a href="http://www.equisearch.com/home">EquiSearch</a>  |  <a href="http://www.discoverhorses.com/" target="_blank">DiscoverHorses.com</a>   |  <a href="http://www.myhorse.com/" target="_blank">MyHorse.com</a>   |  <a href="http://www.horse-journal.com/" target="_blank">Horse Journal</a>   |   <a href="http://americancowboy.com/" target="_blank">American Cowboy</a>   |   <a href="http://stablemanagement.com/home" target="_blank">Stable Management</a>   |   <a href="http://equusmagazine.com/home" target="_blank"></a><a href="http://americancowboy.com/" target="_blank">American Cowboy</a> |  <a href="http://dressagetoday.com/home" target="_blank">Dressage Today</a>   |&nbsp;<a href="http://equusmagazine.com/home" target="_blank">EQUUS</a>  | <a href="http://horseandrider.com/home" target="_blank">Horse&amp;Rider</a> | <a href="http://practicalhorsemanmag.com/home" target="_blank">Practical Horseman</a>   |  <br/><a href="http://spintowinrodeo.com/" target="_blank">Spin-to-Win Rodeo</a>   |  <a href="http://equimanagement.com/" target="_blank">EquiManagement</a>   |  <a href="http://trailridermag.com/home" target="_blank">The Trail Rider</a>   |  <a href="http://www.usrider.org/" target="_blank">US Rider</a></p>
    </div>
   </center>

**Comment by dressagetrainingonline** [comment]
I didn't realize GitHub would convert my HTML. I've uploaded for easy 

source code snippet copy and paste here http://www.angelea.com/mathew/footer.html and because GitHub doesn't allow for attachment of html files. :-/

Thanks! -Angelea

**Comment by itekk** [comment]
Footer content added.

**Comment by itekk** [comment]
can i close this issue?
