### ISSUE TITLE
WebDev updates

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#7]
Hi Mathew. Please let me know how you update the site pages that aren't accessible via admin UI (like copying and pasting the footer details) and what the FTP log in is as it wasn't in Reisa's master list spreadsheet.

My Bachelors degree is Computer Science & I started webdev in 1995 so there's little things here and there (like adding the footer once I know structure) I can do freeing up your time do to more important programming stuff and site enhancements.

TIA!

**Comment by itekk** [comment]
FTP details of DTO is below.

**SFTP**
Port : 22
Host : 104.130.29.96
Username : dtolive
Password : dt0liV31

**DB Navicat with SSH tunnel**
DB Name : dto_livedb
Username : dto_livedbusr
Password : Dt0L!v3dB
Host : 06dac57499655dad021d0c52a494f296aa5b3879.rackspaceclouddb.com

We are using SVN to upload files. Let me know if you need anything else.
