### ISSUE TITLE
Custom Playlist link turns up privacy error page

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#8]
![dto-customplaylist](https://user-images.githubusercontent.com/31981904/31299103-f79bda98-aaba-11e7-975e-24d256ec5e0d.jpg)
Link from Resources/Products drop down to Custom Playlists goes to https://customplaylist.dressagetrainingonline.com/ and is detected as a privacy error page actually.

**Comment by itekk** [comment]
Issue fixed. Please take this link from site.
